In [1]:
import numpy as np

In [9]:
arr = np.array([5, 3, 14, 43, 1])

In [10]:
arr.sort()

In [11]:
arr

array([ 1,  3,  5, 14, 43])

In [12]:
type(arr)

numpy.ndarray

In [14]:
matrix = [2, 4, 6], [7, 3, 1], [10, 20, 30]
matrix = np.array(matrix)
matrix

array([[ 2,  4,  6],
       [ 7,  3,  1],
       [10, 20, 30]])

In [19]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(3, 5)

array([[0.08656044, 0.37048486, 0.63112548, 0.23606434, 0.39620642],
       [0.51251018, 0.0401585 , 0.57315283, 0.36901467, 0.78805826],
       [0.63128089, 0.64975579, 0.92979438, 0.7765758 , 0.39368141]])

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.random.randn(3)

array([ 1.79621718, -1.45097224, -0.25997674])

In [36]:
np.random.randint(2)

1

In [39]:
arr = np.arange(0, 10)

In [40]:
arr.max()

9

In [41]:
arr[0:2] = 90

In [42]:
arr

array([90, 90,  2,  3,  4,  5,  6,  7,  8,  9])

In [43]:
arr[:] = 1

In [44]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [52]:
arr_2d = np.array([
            [2, 4, 6],
            [3, 1, 7],
            [10, 20, 30]
         ])

In [57]:
arr_2d[:, :]

array([[ 2,  4,  6],
       [ 3,  1,  7],
       [10, 20, 30]])

In [69]:
arr2d = np.zeros((5, 5))

In [70]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Pandas

In [71]:
import pandas as pd

## Series

In [75]:
labels = ['a', 'b', 'c']
my_list = [1, 2, 4]
arr = np.array([10, 20, 30])
d = {
    'a': 10,
    'b': 20,
    'c': 30
}

In [76]:
d.values()

dict_values([10, 20, 30])

In [77]:
d.keys()

dict_keys(['a', 'b', 'c'])

## using list

In [79]:
pd.Series(data = my_list, index=labels)

a    1
b    2
c    4
dtype: int64

## using Numpy Array

In [80]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [81]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

## Using index

In [89]:
ser = pd.Series([1, 2, 3, 4], index=["USA", "UAE", "Iran", "Iraq"])

ser

USA     1
UAE     2
Iran    3
Iraq    4
dtype: int64

In [86]:
ser['USA']

1

In [96]:
ser1 = pd.Series([1, 2, 3, 4], index=["USA", "UAE", "Ireland", "Iraq"])

ser1

USA        1
UAE        2
Ireland    3
Iraq       4
dtype: int64

In [97]:
ser + ser1

Iran       NaN
Iraq       8.0
Ireland    NaN
UAE        4.0
USA        2.0
dtype: float64

## DataFrames

In [100]:
# seed means there's a particular number d dataframe is generatibg
from numpy.random import randn
np.random.seed(10)

In [101]:
df = pd.DataFrame(randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())
dfc = pd.DataFrame(randn(5, 4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])

In [103]:
df

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [104]:
dfc

W         X         Y         Z
A -1.977728 -1.743372  0.266070  2.384967
B  1.123691  1.672622  0.099149  1.397996
C -0.271248  0.613204 -0.267317 -0.549309
D  0.132708 -0.476142  1.308473  0.195013
E  0.400210 -0.337632  1.256472 -0.731970

In [105]:
df['X']

A    0.715279
B   -0.720086
C   -0.174600
D    1.028274
E    0.135137
Name: X, dtype: float64

In [107]:
df[['W', 'Y']]

W         Y
A  1.331587 -1.545400
B  0.621336  0.265512
C  0.004291  0.433026
D -0.965066  0.228630
E -1.136602  1.484537

In [108]:
df['new'] = df['X'] + df['Z']
df

W         X         Y         Z       new
A  1.331587  0.715279 -1.545400 -0.008384  0.706895
B  0.621336 -0.720086  0.265512  0.108549 -0.611537
C  0.004291 -0.174600  0.433026  1.203037  1.028437
D -0.965066  1.028274  0.228630  0.445138  1.473412
E -1.136602  0.135137  1.484537 -1.079805 -0.944668

In [112]:
# axis 1 is for col, while axis 0 is for row
# inplace makes the col disappear
df.drop('new', axis=1)

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [111]:
df

W         X         Y         Z       new
A  1.331587  0.715279 -1.545400 -0.008384  0.706895
B  0.621336 -0.720086  0.265512  0.108549 -0.611537
C  0.004291 -0.174600  0.433026  1.203037  1.028437
D -0.965066  1.028274  0.228630  0.445138  1.473412
E -1.136602  0.135137  1.484537 -1.079805 -0.944668

In [114]:
df.drop('E', axis=0)

W         X         Y         Z       new
A  1.331587  0.715279 -1.545400 -0.008384  0.706895
B  0.621336 -0.720086  0.265512  0.108549 -0.611537
C  0.004291 -0.174600  0.433026  1.203037  1.028437
D -0.965066  1.028274  0.228630  0.445138  1.473412

In [115]:
df

W         X         Y         Z       new
A  1.331587  0.715279 -1.545400 -0.008384  0.706895
B  0.621336 -0.720086  0.265512  0.108549 -0.611537
C  0.004291 -0.174600  0.433026  1.203037  1.028437
D -0.965066  1.028274  0.228630  0.445138  1.473412
E -1.136602  0.135137  1.484537 -1.079805 -0.944668

In [118]:
df.drop('new', axis=1, inplace=True)

In [119]:
df

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [122]:
# selecting row
df.loc['B']

W    0.621336
X   -0.720086
Y    0.265512
Z    0.108549
Name: B, dtype: float64

In [123]:
# df > 0 returns true for the df values that are greater than0
df>0

W      X      Y      Z
A   True   True  False  False
B   True  False   True   True
C   True  False   True   True
D  False   True   True   True
E  False   True   True  False

In [124]:
df<1

W      X      Y      Z
A  False   True   True   True
B   True   True   True   True
C   True   True   True  False
D   True  False   True   True
E   True   True  False   True

In [125]:
df[df>0]

W         X         Y         Z
A  1.331587  0.715279       NaN       NaN
B  0.621336       NaN  0.265512  0.108549
C  0.004291       NaN  0.433026  1.203037
D       NaN  1.028274  0.228630  0.445138
E       NaN  0.135137  1.484537       NaN

In [127]:
df[df['X'] > 0]

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [128]:
df[df['X'] > 0]['Z']

A   -0.008384
D    0.445138
E   -1.079805
Name: Z, dtype: float64